# Generated by Django 5.1.7 on 2025-03-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('movie_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('time_slot', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
